# Generated by Django 4.2.11 on 2024-05-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=datetime.datetime(2024, 5, 1, 17, 43, 3, 186243, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
